use pest3_generator::typed::derive_typed_parser;
use quote::quote;
use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
};

fn normalize(path: &Path) -> PathBuf {
    let path = path.to_string_lossy();
    PathBuf::from(path.strip_prefix(r#"\\?\"#).unwrap_or(&path))
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let grammar = normalize(&manifest_dir.join("../meta/src/grammar_bootstrap.pest"));
    let output = normalize(&manifest_dir.join("../meta/src/grammar.rs"));

    let grammar_path = grammar.to_string_lossy();
    let derived = derive_typed_parser(
        quote! {
            #[grammar = #grammar_path]
            pub struct PestParser;
        },
        false,
        true,
    );

    let generated = format!(
        "// @generated by `cargo run --manifest-path bootstrap/Cargo.toml`\n\
         // Do not edit by hand.\n\n\
         pub struct PestParser;\n{}\n",
        derived
    );
    fs::write(&output, generated).expect("failed to write generated meta parser");

    let _ = Command::new("rustfmt").arg(&output).status();
}
