string = "abc"
insensitive = i"abc"
range = '0'..'9'
ident = string
pos_pred = &string
neg_pred = !string
double_neg_pred = !!string
sequence_atomic = string - string
sequence_optional_trivia = string ~ string
sequence_mandatory_trivia = string ^ string
sequence_nested = string ~ string
sequence_compound_nested = sequence_nested
choice = string | range
choice_prefix = | string | range
optional = string?
repeat = string~*
repeat_atomic = string*
repeat_once = string~+
repeat_once_atomic = string+
repeat_min_max = string~{2..3}
repeat_min_max_atomic = string{2..3}
repeat_exact = string~{2}
repeat_min = string~{2..}
repeat_min_atomic = string{2..}
repeat_max = string~{..2}
repeat_max_atomic = string{..2}
soi_at_start = pest::soi - string
repeat_mutate_stack = (pest::stack::push('a'..'c') - ",")* - pest::stack::pop - pest::stack::pop - pest::stack::pop
repeat_mutate_stack_pop_all = (pest::stack::push('a'..'c') - ",")* - pest::stack::pop_all
will_fail = repeat_mutate_stack_pop_all - "FAIL"
stack_resume_after_fail = will_fail | repeat_mutate_stack_pop_all
peek_ = pest::stack::push(range) - pest::stack::push(range) - pest::stack::peek - pest::stack::peek
peek_all = pest::stack::push(range) - pest::stack::push(range) - pest::stack::peek_all
peek_slice_23 = pest::stack::push(range) - pest::stack::push(range) - pest::stack::push(range) ~ pest::stack::push(range) ~ pest::stack::push(range) ~ pest::stack::peek[1..-2]
pop_ = pest::stack::push(range) - pest::stack::push(range) - pest::stack::pop - pest::stack::pop
pop_all = pest::stack::push(range) - pest::stack::push(range) - pest::stack::pop_all
pop_fail = pest::stack::push(range) - !pest::stack::pop - range - pest::stack::pop
checkpoint_restore = pest::stack::push("") - (pest::stack::push("a") - "b" - pest::stack::pop | pest::stack::drop - "b" | pest::stack::pop - "a") - pest::eoi
longchoice_builtin = ( "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16")
longseq_builtin = ( "01" ~ "02" ~ "03" ~ "04" ~ "05" ~ "06" ~ "07" ~ "08" ~ "09" ~ "10" ~ "11" ~ "12" ~ "13" ~ "14" ~ "15" ~ "16")
longchoice_critical = ( "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17")
longseq_critical = ( "01" ~ "02" ~ "03" ~ "04" ~ "05" ~ "06" ~ "07" ~ "08" ~ "09" ~ "10" ~ "11" ~ "12" ~ "13" ~ "14" ~ "15" ~ "16" ~ "17")
longchoice_jump = ( "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" | "19")
longseq_jump = ( "01" ~ "02" ~ "03" ~ "04" ~ "05" ~ "06" ~ "07" ~ "08" ~ "09" ~ "10" ~ "11" ~ "12" ~ "13" ~ "14" ~ "15" ~ "16" ~ "17" ~ "18" ~ "19")
/*
ascii_digits = ascii_digit+
ascii_nonzero_digits = ascii_nonzero_digit+
ascii_bin_digits = ascii_bin_digit+
ascii_oct_digits = ascii_oct_digit+
ascii_hex_digits = ascii_hex_digit+
ascii_alpha_lowers = ascii_alpha_lower+
ascii_alpha_uppers = ascii_alpha_upper+
ascii_alphas = ascii_alpha+
ascii_alphanumerics = ascii_alphanumeric+
asciis = ascii+
newline = newline+
unicode = XID_START - XID_CONTINUE*
SYMBOL = "shadows builtin"

han = HAN+
hangul = HANGUL+
hiragana = HIRAGANA+
arabic = ARABIC+
emoji = EMOJI+
*/

~ = (" " | "$")*
^ = (" " | "$")+

// Line comment

/* 1-line multiline comment */

/*
	N-line multiline comment
*/

/*
	// Line comment inside multiline

	/*
		(Multiline inside) multiline
	*/

	Invalid segment of grammar below (repeated rule)

	WHITESPACE = _"hi"
*/
